spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Laxman1436@
    url: jdbc:mysql://localhost:3306/sbms29
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    batch.jdbc.initialize-schema: ALWAYS
